socket:
  server:
    core-count: 6
    total-count: 10
    port: 9998
    keep-alive: 10
    enable: true
spring:
  redis:
    port: 6379
    host: 127.0.0.1
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=diplomaProject;
    username: sa
    password: 1111
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
pagehelper:
  helperDialect: sqlserver
  reasonable: true
  supportMethodsArguments: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: session
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
#    cache-enabled: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.white.pojo

logging:
  charset:
    console: utf-8
  pattern:
    console: '%boldMagenta(%d{yyyy-MM-dd HH:mm:ss})  [%p]  %highlight(%C:%L)  : %m %n'
